"""Assemble the single native-installable companion from reviewed source modules."""
from pathlib import Path
import hashlib
import json
HERE=Path(__file__).parent
def build():
    parts=['# Generated by build_bundle.py. Edit source modules, regenerate, then test.\n']
    for name in ('action.py','history.py','native.py'):
        source=(HERE/name).read_text(encoding='utf-8')
        source='\n'.join(line for line in source.splitlines() if not line.startswith(('from action import ','from history import ')))+'\n'
        parts.append('\n# SOURCE: '+name+'\n'+source)
    parts.append('''
if __name__ == '__main__':
    import argparse
    ap=argparse.ArgumentParser(description='Validate a complete synthetic action export; not authenticated admission or execution.')
    ap.add_argument('export_directory')
    args=ap.parse_args()
    print(json.dumps(verify_export(args.export_directory),indent=2))
''')
    raw=''.join(parts).encode('utf-8')
    compile(raw,'action_bundle.py','exec')
    (HERE/'action_bundle.py').write_bytes(raw)
    return {'bundleSha256':hashlib.sha256(raw).hexdigest(),'sources':{n:hashlib.sha256((HERE/n).read_bytes()).hexdigest() for n in ('action.py','history.py','native.py','build_bundle.py','action.schema.json')}}
if __name__=='__main__':
    (HERE/'bundle-build.json').write_text(json.dumps(build(),indent=2)+'\n',encoding='utf-8',newline='\n')
